version: '3.9'

services:
  django:
    build:
      context: .
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn sharedmusic.wsgi --bind 0.0.0.0:${HTTP_PORT} --workers=2
      "
    volumes:
      - ./sharedmusic:/sharedmusic
      - django:/vol/web/static
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    env_file: .env
    depends_on:
      - db
      - redis

  daphne-ws:
    build:
      context: .
    command: wait-for-it.sh django:${HTTP_PORT} -s -t 120 -- daphne -b 0.0.0.0 -p ${WS_PORT} sharedmusic.asgi:application
    volumes:
      - ./sharedmusic:/sharedmusic
    ports:
      - ${WS_PORT}:${WS_PORT}
    env_file: .env
    depends_on:
      - db
      - redis
      - django

  celery-worker:
    build: .
    command: wait-for-it.sh django:${HTTP_PORT} -s -t 120 -- celery -A sharedmusic worker --loglevel=INFO --beat
    volumes:
      - ./sharedmusic:/sharedmusic
    env_file: .env
    depends_on:
      - db
      - redis
      - django

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:${PORT}
    env_file: .env
    volumes:
      - django:/var/www/static
      # To keep static frontend changes
      - ./sharedmusic/main/static/js:/var/www/static/js
      - ./sharedmusic/main/static/css:/var/www/static/css
      - ./sharedmusic/main/static/images:/var/www/static/images
    depends_on:
      - django

  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - redis-data:/data

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - ./backups:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@every 1m
      - BACKUP_KEEP_DAYS=2
      - BACKUP_KEEP_WEEKS=2
      - BACKUP_KEEP_MONTHS=2
      - HEALTHCHECK_PORT=8080

volumes:
  django:
  postgres-data:
  redis-data:

  #lint:
  #  build: .
  #  command: >
  #    sh -c "
  #      flake8 --max-line-length 120 --exclude migrations,venv,manage.py,__init__.py
  #    "
  #  volumes: 
  #    - ./sharedmusic:/sharedmusic
  #  env_file: .env
  #  depends_on:
  #    - db

  #filldb:
  #  build: .
  #  command: >
  #    sh -c "
  #      python manage.py wait_for_db &&
  #      python manage.py makemigrations &&
  #      python manage.py migrate && 
  #      python manage.py loaddata fixtures/dev.json
  #    "
  #  volumes: 
  #    - ./sharedmusic:/sharedmusic
  #  env_file: .env
  #  depends_on:
  #    - db
  #  profiles: ["init"]

  #test:
  #  build:
  #    context: .
  #  user: "${UID}"
  #  command: >
  #    sh -c "
  #      python manage.py wait_for_db &&
  #      coverage run --source='.' manage.py test mainapp.tests &&
  #      coverage xml
  #    "
  #  volumes: 
  #    - ./sharedmusic:/sharedmusic
  #  env_file: .env
  #  depends_on: 
  #    - db
