# Generated by Django 3.2.13 on 2022-04-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_visited',
            field=models.DateTimeField(auto_now=True, verbose_name='Last visited'),
        ),
    ]
