# Generated by Django 3.2.13 on 2022-05-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomplaylisttrack',
            options={'ordering': ['-id'], 'verbose_name': 'Room playlist track', 'verbose_name_plural': 'Room playlist tracks'},
        ),
        migrations.AddField(
            model_name='room',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='roomplaylisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='main.roomplaylist', verbose_name='Room playlist'),
        ),
    ]
