# Generated by Django 3.2.13 on 2022-05-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='main.playlist', verbose_name='Playlist')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.soundtrack', verbose_name='Soundtrack')),
            ],
            options={
                'verbose_name': 'Playlist track',
                'verbose_name_plural': 'Playlist tracks',
                'ordering': ['-id'],
            },
        ),
    ]
