# Generated by Django 4.0.4 on 2022-04-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundtrack',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='soundtrack',
            name='order',
        ),
        migrations.RemoveField(
            model_name='soundtrack',
            name='playlists',
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('soundtrack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.soundtrack', verbose_name='Soundtrack')),
            ],
            options={
                'verbose_name': 'Playlist Item',
                'verbose_name_plural': 'Playlist Items',
                'ordering': ['-id'],
            },
        ),
    ]
