# Generated by Django 4.0.4 on 2022-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Code'),
        ),
    ]
