# Generated by Django 3.2.13 on 2022-05-27 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220527_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ban_list',
            field=models.ManyToManyField(blank=True, related_name='ban_list', to=settings.AUTH_USER_MODEL, verbose_name='Ban list'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_connections',
            field=models.IntegerField(default=20, verbose_name='Max connections'),
        ),
    ]
