# Generated by Django 3.2.13 on 2022-05-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220509_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.soundtrack', verbose_name='Soundtrack'),
        ),
    ]
