# Keys
ERROR_KEY = "error"
SUCCESS_KEY = "success"

# Messages
ROOM_NOT_FOUND = "Room not found."
LISTENER_ADDED = "Listener added."
LISTENER_REMOVED = "Listener removed."
USER_ALREADY_IN_ROOM = "User has already connected. Refresh the page."
# Format: "<username> has disconnected."
USER_DISCONNECTED = "has disconnected."

# Group prefixes
# Format: "<prefix>_<name>"
ROOM_GROUP_PREFIX = "room"
USER_GROUP_PREFIX = "user"

# Events
CONNECT_EVENT = "CONNECT"
DISCONNECT_EVENT = "DISCONNECT"
ALREADY_CONNECTED_EVENT = "ALREADY_CONNECTED"
CHANGE_TRACK_EVENT = "CHANGE_TRACK"
#CHANGE_TRACK_ERROR_EVENT = "CHANGE_TRACK_ERROR"
NEW_USER_JOINED_EVENT = "NEW_USER_JOINED"
SET_CURRENT_TRACK_EVENT = "SET_CURRENT_TRACK"
CHANGE_TIME_EVENT = "CHANGE_TIME"
SEND_TRACK_TO_NEW_USER = "SEND_TRACK_TO_NEW_USER"
ADD_TRACK_EVENT = "ADD_TRACK"
ADD_TRACK_ERROR_EVENT = "ADD_TRACK_ERROR"
