name: CD

on:
  release:
    types: [published]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull ${{ secrets.REPO_URL }}
            docker-compose down
            docker rmi -f $(docker images -aq)
            docker volume rm shared-music_django
            docker-compose -f docker-compose-deploy.yml up -d
