name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cat .env.sample >> .env
          docker-compose up --exit-code-from test test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull ${{ secrets.REPO_URL }}
            docker-compose down
            docker rmi -f $(docker images -aq)
            docker-compose -f docker-compose-deploy.yml up -d
